### ISSUE TITLE
Organization ID required for JC accounts using Multi-Tenant Portal

### ISSUE THREAD

**Issue by kylelundstedt** [CognotektGmbH/terraform-provider-jumpcloud#12]
Hi all,

I believe that, in the past, the `api_key` also served to uniquely identify your JumpCloud account.  However, JumpCloud currently offers a "Multi-tenant Portal" for companies that manage multiple JumpCloud accounts (i.e., big companies, managed servicer providers, etc).  The API reference is https://docs.jumpcloud.com/1.0/organizations/get-organization-details.

Unfortunately, that means all of the resources provided by this `terraform-provider-jumpcloud` are not available to "Multi-Tenant Portal" accounts.  Any request generates a "Unauthorized:  no organization selected" error, like below:

```
jumpcloud_user_group.test_group: Creating...

Error: error creating user group test_group: Status: 401 Unauthorized, Body: {"message":"Unauthorized: no organization selected"} - response = &{Status:401 Unauthorized StatusCode:401 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Length:[52] Content-Type:[application/json; charset=utf-8] Date:[Fri, 22 Nov 2019 18:57:21 GMT] Etag:[W/"34-n2aV4pQxUMFBo3vvV2dC+vSjcpo"] Server:[nginx] X-Response-Time:[9.065ms]] Body:0xc00020c880 ContentLength:52 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0xc000457700 TLS:0xc000331080}
```

At this point, I think that each api_key is associated with multiple organization IDs.  I think all that is needed to have the provider work for these accounts is to input a specific organization ID to the provider definition.  

Thanks for considering this addition!

**Comment by daniellohausen** [comment]
Hi @kylelundstedt ,

thanks for your interest in our provider. I have created a branch with a new version using the x-org-id, see https://github.com/CognotektGmbH/terraform-provider-jumpcloud/tree/dln/add-x-org.

Are you able to compile the provider and test if it works also in your scenario? That would be nice.

**Comment by kylelundstedt** [comment]
@daniellohausen, thanks for the quick reply!
When I try to build from the new branch, I get the following error:
```
~/g/s/terraform-provider-jumpcloud (master|✔) [2] $ make build                                                                                   (2) (308ms) ┃
go build -o terraform-provider-jumpcloud
go: github.com/hashicorp/hcl2@v0.0.0-20190618164755-0b64543c968c: invalid pseudo-version: does not match version-control timestamp (2019-06-18T16:38:56Z)
make: *** [build] Error 1
```
I'm not a Go programmer, so my apologies if this is easy to fix.
I'm using go version go1.13.3 darwin/amd64.

**Comment by daniellohausen** [comment]
@kylelundstedt ; Sorry for that. It seems to be a dependency issue within terraform (we only declare  github.com/hashicorp/terraform as a module dependency, but terraform itself has dozens of their own deps - If you are interested, you can look at go.mod in the terraform github repo).

I cannot reproduce it now so will simply attach a amd64 binary for testing. If that does not work for, you can try recreating the dependencies by executing:
rm go.mod
rm go.sum
go mod init

**Comment by daniellohausen** [comment]
[terraform-provider-jumpcloud.zip](https://github.com/CognotektGmbH/terraform-provider-jumpcloud/files/3890701/terraform-provider-jumpcloud.zip)

**Comment by kylelundstedt** [comment]
Rats.  Downloaded the binary into the plugin directory, and got the following error:

```
❯ terraform plan                                                                       (1s 397ms)

Error: Failed to instantiate provider "jumpcloud" to obtain schema: fork/exec /Users/kyle/.terraform.d/plugins/terraform-provider-jumpcloud: exec format error
```

Then, removed the go.mod and go.sum files, and ran `go mod init`.  Got lots of activity, then an error at the end:
```
...
go: finding github.com/google/uuid v1.1.1
go: finding github.com/hashicorp/golang-lru v0.5.1
# github.com/cognotektgmbh/terraform-provider-jumpcloud/jumpcloud
../../../pkg/mod/github.com/cognotektgmbh/terraform-provider-jumpcloud@v0.1.0/jumpcloud/types.go:15:13: undefined: v2.UserGroupPostAttributes
make: *** [build] Error 2
```

Sorry that it's not working.  Happy to continue testing for you!!!
I appreciate the effort.

**Comment by daniellohausen** [comment]
Hm that is weird, a couple of questions to narrow things down: 
- Are you using TF 0.12.16 (I updated the dependency on the MR)
- Did you run terraform init again before the plan?
- You are using a linux OS as a client, right?

**Comment by kylelundstedt** [comment]
I am using TF 0.12.16.
I did re-run TF init.
I'm using macOS 10.15.1.

Holding aside the compilation issues, I have a question about the binary that I downloaded.  The error is "Unauthorized: no organization selected".

From the updated README, I thought both the api key and the org id needed to be exported into environment variables in the shell.  So, running `env` at the command line shows:

```
...
JUMPCLOUD_API_KEY=xxxxxxxxxx
JUMPCLOUD_ORG_ID=yyyyyyyyyy
...
```

However, I still get the "unauthorized" message.

I also went back to your original code in the examples folder, which has the API key in the provider definition.  So, I just added the Org ID there :

```
provider "jumpcloud" {
  api_key = "xxxxxxxxxx"
  org_id = "yyyyyyyyyy"
}
```

That gives the same "unauthorized" error.  Am I not inputting the org_id info correctly?

**Comment by daniellohausen** [comment]
You are correct, its JUMPCLOUD_ORG_ID. When I run my tests with a wrong org ID, the API returns "Error: Status: 404 Not Found, Body: Not Found: selected organization not found" , which is reasonable. I don't get any errors when I export the correct org ID.  

I am confused if you can use the attached provider binary or not. It was compiled for Linux so it should not. I can cross-compile for Mac if that is needed.

**Comment by kylelundstedt** [comment]
I assumed the Linux binary would work on my Mac.  Could I be getting the `Error: error creating user group test_group: Status: 401 Unauthorized, Body: {"message":"Unauthorized: no organization selected"}` because somehow the Linux version of the provider doesn't work on the Mac?  If you cross-compile for the Mac and send me that version, I can test.

**Comment by daniellohausen** [comment]
I doubt it, because it seems to use the API_KEY you have provided. I will anyways attach a Mac binary

**Comment by daniellohausen** [comment]
[terraform-provider-jumpcloud-mac.zip](https://github.com/CognotektGmbH/terraform-provider-jumpcloud/files/3902485/terraform-provider-jumpcloud-mac.zip)

**Comment by kylelundstedt** [comment]
Whoo-hooo!!!!  That did it.  👍👍👍

Follow-up question in the next issue.  😁
