### ISSUE TITLE
Feature request:  set JC password using TF

### ISSUE THREAD

**Issue by kylelundstedt** [CognotektGmbH/terraform-provider-jumpcloud#13]
@daniellohausen, now that the provider is working on my Mac, here's a follow-up question.  I believe that the JC API allows you to set a password immediately when you create a new user, rather than sending an email to that user and having them create the password.  I'd like to use TF to create a password (using the `random_password` provider) and assign that random password to the new user created by the `jumpcloud_user` resource.  Is that possible?  I've added some sample code below.  We use 1Password for Teams to save shared logins, FWIW.

```
provider "jumpcloud" {
}

provider "onepassword" {
  subdomain = "xyz"
}

resource "random_password" "password" {
  length = 16
}

resource "jumpcloud_user" "test_user1" {
  email      = "klundstedt+testuser1@xyz.com"
  username   = "testuser1"
  # password = random_password.password.result
  firstname  = "test"
  lastname   = "user1"
}

resource "onepassword_item_login" "this" {
  name  = "${jumpcloud_user.test_user1.firstname} ${jumpcloud_user.test_user1.lastname}"
  username = jumpcloud_user.test_user1.username
  # password =  jumpcloud_user.test_user1.password
  url   = "https://console.jumpcloud.com"
  vault    = "Team"
}

resource "jumpcloud_user_group" "test_group" {
  name = "test_group"
}

resource "jumpcloud_user_group_membership" "test_membership" {
  userid  = jumpcloud_user.test_user1.id
  groupid = jumpcloud_user_group.test_group.id
}
```

**Comment by daniellohausen** [comment]
@kylelundstedt : With this approach, the initial password would end up in the TF state and when the user changes it (What he should!), subsequent TF-plans would show this as a difference.

Instead, you could use local-exec and curl to set the password directly via the APi ( https://www.terraform.io/docs/provisioners/index.html )

**Comment by kylelundstedt** [comment]
Thanks for the good advice, @daniellohausen.  I'lll try the local-exec or post-hook options for adding a random password.
